/** constants related to ordering */
export const GET_SHIPPING_REGIONS = "order/GET_SHIPPING_REGIONS";
export const GET_SHIPPING_REGIONS_SUCCESS =
  "order/GET_SHIPPING_REGIONS_SUCCESS";
export const GET_SHIPPING_REGIONS_FAILED = "order/GET_SHIPPING_REGIONS_FAILED";

export const GET_REGION_DETAILS = "order/GET_REGION_DETAILS";
export const GET_REGION_DETAILS_SUCCESS = "order/GET_REGION_DETAILS_SUCCESS";
export const GET_REGION_DETAILS_FAILED = "order/GET_REGION_DETAILS_FAILED";

export const GET_TAX = "order/GET_TAX";
export const GET_TAX_SUCCESS = "order/GET_TAX_SUCCESS";
export const GET_TAX_FAILED = "order/GET_TAX_FAILED";

export const CREATE_ORDER = "order/CREATE_ORDER";
export const CREATE_ORDER_SUCCESS = "order/CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "order/CREATE_ORDER_FAILED";
