/** constants for home page */
export const GET_PRODUCTS = "home/GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "home/GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "home/GET_PRODUCTS_FAILED";

export const GET_PRODUCTS_BY_DEPT = "home/GET_PRODUCTS_BY_DEPT";
export const GET_PRODUCTS_BY_DEPT_SUCCESS = "home/GET_PRODUCTS_BY_DEPT_SUCCESS";
export const GET_PRODUCTS_BY_DEPT_FAILED = "home/GET_PRODUCTS_BY_DEPT_FAILED";

export const GET_PRODUCTS_BY_CAT = "home/GET_PRODUCTS_BY_CAT";
export const GET_PRODUCTS_BY_CAT_SUCCESS = "home/GET_PRODUCTS_BY_CAT_SUCCESS";
export const GET_PRODUCTS_BY_CAT_FAILED = "home/GET_PRODUCTS_BY_CAT_FAILED";

export const SEARCH_PRODUCT = "home/SEARCH_PRODUCT";
export const SEARCH_PRODUCT_SUCCESS = "home/SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_FAILED = "home/SEARCH_PRODUCT_FAILED";

export const GET_PRODUCT_DETAILS_ATTRS = "home/GET_PRODUCT_DETAILS_ATTRS";
export const GET_PRODUCT_DETAILS_ATTRS_SUCCESS =
  "home/GET_PRODUCT_DETAILS_ATTRS_SUCCESS";
export const GET_PRODUCT_DETAILS_ATTRS_FAILED =
  "home/GET_PRODUCT_DETAILS_ATTRS_FAILED";

export const SUBMIT_REVIEW = "home/SUBMIT_REVIEW";

export const TOGGLE_MODAL = "home/TOGGLE_MODAL";

export const CHANGE_CURRENT_PAGE = "home/CHANGE_CURRENT_PAGE";
